name: ci-workflow

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  run_unit_tests:
    name: 🔎 Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: 'npm'
      - run: npm ci
      - run: npm run test
